### ISSUE TITLE
Implement :open and :tabopen

### ISSUE THREAD

**Issue by shinglyu** [shinglyu/QuantumVim#11]
shortcut: `o` == `:open`. `t` == `:tabopen`.

**Comment by johnathan79717** [comment]
How about using keys 'o' and 't' just like pentadactyl?

**Comment by johnathan79717** [comment]
We can focus the awesome bar (although I don't know how to do that with web extensions).  With 't' we open a new tab first.

**Comment by shinglyu** [comment]
Yes, I just updated the first comment. And I have the exact same idea in mind. Let's focus on awesomebar instead of implementing out own. And perhaps select all the URL or even clear all the text in the awesomebar?

**Comment by shinglyu** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1295072
